mod token;
pub use token::{Token, TokenType};
pub use token::{ASSIGN, ASTERISK, BANG, COMMA, EOF, FUNCTION, GT, IDENT, ILLEGAL, INT, LBRACE, LET, EQ, NOT_EQ};
pub use token::{LPAREN, LT, MINUS, PLUS, RBRACE, RPAREN, SEMICOLON, SLASH, TRUE, FALSE, IF, ELSE, RETURN};