mod token;
pub use token::{Token, TokenType};
pub use token::{ASSIGN, ASTERISK, BANG, COMMA, EOF, FUNCTION, GT, IDENT, ILLEGAL, INT, LBRACE, LET, LPAREN, LT, MINUS, PLUS, RBRACE, RPAREN, SEMICOLON, SLASH};